apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-app-backend-deployment
  labels:
    app: loan-app-backend
spec:
  replicas: 1  # You can adjust the number of replicas
  selector:
    matchLabels:
      app: loan-app-backend
  template:
    metadata:
      labels:
        app: loan-app-backend
    spec:
      containers:
        - name: loan-app-backend
          image: tgirase/loan-app-backend:0.0.2  # Replace with your Docker Hub image
          ports:
            - containerPort: 8080
          env:
            - name: loan_app_someprop
              value: "value-from-uat"
          resources:  # Optional: Define resource limits
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:  # Optional: Liveness probe
            httpGet:
              path: /actuator/health  # Adjust if using Spring Boot Actuator
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:  # Optional: Readiness probe
            httpGet:
              path: /actuator/health  # Adjust if using Spring Boot Actuator
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: loan-app-backend-service
spec:
  type: NodePort  # Change ClusterIP to NodePort
  selector:
    app: loan-app-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001  # Choose a port between 30000 and 32767
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loan-app-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: loan-app-backend.local  # This is the domain name to access your app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loan-app-backend-service
                port:
                  number: 80
